# Configuration of the Cycloid stack
name: 'k8s-runner'
canonical: 'stack-k8s-runner'
description: 'Used to manage resources deployed on a Kubernetes cluster with plain YAML or JSON manifests.'
keywords:
  - 'kubernetes'
  - 'eks'
  - 'gke'
  - 'onprem'
  - 'aws'
  - 'gcloud'
author: 'Cycloid'
image: 'https://raw.githubusercontent.com/cycloid-community-catalog/stack-k8s-runner/master/icon.png'
type: 'stack'
technologies:
  - technology: Kubernetes
    version: 1.15+
config:
  # Configuration of the CI pipeline
  pipeline:
    pipeline:
      path: 'pipeline/pipeline.yml'
    variables:
      path: 'pipeline/variables.sample.yml'
