---
default:
  pipeline:
    k8s:
      - name: "k8s kubeconfig"
        description: "Kubernetes config used to connect to the cluster."
        key: k8s_kubeconfig
        type: string
        widget: cy_cred
        default: "((custom_kubeconfig))"
      - name: "Kubernetes version"
        description: "Kubernetes version for the concourse resource used to apply your manifests."
        key: k8s_version
        widget: simple_text
        type: string
        default: "1.15"
      - name: "Manifests path"
        description: "Path to the manifest(s) to apply in the config git repository, can be either a folder or a single file."
        key: k8s_path
        widget: simple_text
        type: string
        default: "($ project $)/k8s/($ environment $)"
      - name: "Wait ready selector"
        description: "Used to tell the concourse kubernetes resource to wait for a certain label selector to be ready."
        key: k8s_wait_ready_selector
        widget: simple_text
        type: string
        default: ""
    Repos:
      - name: "Config repository"
        key: config_git_repository
        type: string
        widget: cy_crs
        description: "Git repository URL containing the config of the stack."
        default: "git@github.com:MyUser/config.git"
        required: true
      - name: "Config git key"
        description: "SSH key pair to fetch the config Git repository."
        key: config_git_private_key
        type: string
        widget: cy_cred
        default: "((ssh_config.ssh_key))"
        required: true
      - name: "Config branch"
        description: "Branch of the config Git repository."
        key: config_git_branch
        widget: cy_branch
        type: string
        description: "The branch used by the config repository"
        source: config_git_repository
        default: "config"
        required: true


eks:
  pipeline:
    aws:
      - name: "AWS access key"
        description: "Amazon AWS access key for Terraform."
        key: aws_access_key
        widget: cy_cred
        type: string
        default: "((aws.access_key))"
      - name: "AWS secret key"
        description: "Amazon AWS secret key for Terraform."
        key: aws_secret_key
        widget: cy_cred
        type: string
        default: "((aws.secret_key))"
    k8s:
      - name: "k8s kubeconfig"
        description: "Kubernetes config used to connect to the cluster."
        key: k8s_kubeconfig
        type: string
        widget: cy_cred
        default: "((custom_kubeconfig))"
      - name: "Kubernetes version"
        description: "Kubernetes version for the concourse resource used to apply your manifests."
        key: k8s_version
        widget: simple_text
        type: string
        default: "1.15"
      - name: "Manifests path"
        description: "Path to the manifest(s) to apply in the config git repository, can be either a folder or a single file."
        key: k8s_path
        widget: simple_text
        type: string
        default: "($ project $)/k8s/($ environment $)"
      - name: "Wait ready selector"
        description: "Used to tell the concourse kubernetes resource to wait for a certain label selector to be ready."
        key: k8s_wait_ready_selector
        widget: simple_text
        type: string
        default: ""
    Repos:
      - name: "Config repository"
        key: config_git_repository
        type: string
        widget: cy_crs
        description: "Git repository URL containing the config of the stack."
        default: "git@github.com:MyUser/config.git"
        required: true
      - name: "Config git key"
        description: "SSH key pair to fetch the config Git repository."
        key: config_git_private_key
        type: string
        widget: cy_cred
        default: "((ssh_config.ssh_key))"
        required: true
      - name: "Config branch"
        description: "Branch of the config Git repository."
        key: config_git_branch
        widget: cy_branch
        type: string
        description: "The branch used by the config repository"
        source: config_git_repository
        default: "config"
        required: true


gke:
  pipeline:
    gcp:
      - name: "GCP json credentials"
        description: "GCP credentials in json format which should be used"
        key: gcp_credentials_json
        widget: cy_cred
        type: string
        default: "((gcp.json_key))"
    k8s:
      - name: "k8s kubeconfig"
        description: "Kubernetes config used to connect to the cluster."
        key: k8s_kubeconfig
        type: string
        widget: cy_cred
        default: "((custom_kubeconfig))"
      - name: "Kubernetes version"
        description: "Kubernetes version for the concourse resource used to apply your manifests."
        key: k8s_version
        widget: simple_text
        type: string
        default: "1.15"
      - name: "Manifests path"
        description: "Path to the manifest(s) to apply in the config git repository, can be either a folder or a single file."
        key: k8s_path
        widget: simple_text
        type: string
        default: "($ project $)/k8s/($ environment $)"
      - name: "Wait ready selector"
        description: "Used to tell the concourse kubernetes resource to wait for a certain label selector to be ready."
        key: k8s_wait_ready_selector
        widget: simple_text
        type: string
        default: ""
    Repos:
      - name: "Config repository"
        key: config_git_repository
        type: string
        widget: cy_crs
        description: "Git repository URL containing the config of the stack."
        default: "git@github.com:MyUser/config.git"
        required: true
      - name: "Config git key"
        description: "SSH key pair to fetch the config Git repository."
        key: config_git_private_key
        type: string
        widget: cy_cred
        default: "((ssh_config.ssh_key))"
        required: true
      - name: "Config branch"
        description: "Branch of the config Git repository."
        key: config_git_branch
        widget: cy_branch
        type: string
        description: "The branch used by the config repository"
        source: config_git_repository
        default: "config"
        required: true
