groups:

- name: overview
  jobs:
  - kubernetes-plan
  - kubernetes-apply

- name: destroy
  jobs:
  - kubernetes-delete

resource_types:

- name: kubernetes
  type: docker-image
  source:
    repository: cycloid/kubernetes-resource
    tag: ((k8s_version))

resources:

- name: git_config-k8s
  type: git
  icon: git
  source:
    uri: ((config_git_repository))
    branch: ((config_git_branch))
    private_key: ((config_git_private_key))
    paths:
      - ((k8s_path))/*

- name: k8s
  type: kubernetes
  icon: kubernetes
  source:
    kubeconfig: ((k8s_kubeconfig))
    aws_access_key_id: ((aws_access_key))
    aws_secret_access_key: ((aws_secret_key))

jobs:

- name: kubernetes-plan
  serial: true
  max_in_flight: 1
  build_logs_to_retain: 10
  plan:
    - do:
      - get: git_config-k8s
        trigger: true

      - task: download aws-iam-authenticator
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: alpine
              tag: latest
          run:
            path: sh
            args:
              - '-exc'
              - |
                apk add -q --no-cache --no-progress curl
                mkdir -p ./aws/bin/
                curl -sSLo ./aws/bin/aws-iam-authenticator "https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/download/v0.4.0/aws-iam-authenticator_0.4.0_linux_amd64"
                chmod +x ./aws/bin/aws-iam-authenticator
          outputs:
            - name: aws

      - try:
          task: weaveworks kubediff
          config:
            platform: linux
            image_resource:
              type: docker-image
              source:
                repository: weaveworks/kubediff
                tag: latest
            run:
              path: sh
              args:
                - '-ec'
                - |
                  export PATH=$PWD/aws/bin:$PATH
                  echo "$KUBECONFIG" > .kubeconfig
                  kubediff --kubeconfig=.kubeconfig git_config-k8s/((k8s_path))
            inputs:
              - name: git_config-k8s
              - name: aws
          params:
            KUBECONFIG: ((k8s_kubeconfig))
            AWS_ACCESS_KEY_ID: ((aws_access_key))
            AWS_SECRET_ACCESS_KEY: ((aws_secret_key))

      - try:
          put: kubectl diff
          resource: k8s
          params:
            kubectl: |
              diff -f git_config-k8s/((k8s_path)) --recursive

      - put: kubectl apply dry-run
        resource: k8s
        params:
          kubectl: |
            apply --server-dry-run -f git_config-k8s/((k8s_path)) --recursive
          wait_until_ready_selector: ((k8s_wait_ready_selector))

- name: kubernetes-apply
  serial: true
  max_in_flight: 1
  build_logs_to_retain: 10
  plan:
    - do:
      - get: git_config-k8s
        trigger: false
        passed:
          - kubernetes-plan

      - put: kubectl apply
        resource: k8s
        params:
          kubectl: |
            apply -f git_config-k8s/((k8s_path)) --recursive
          wait_until_ready_selector: ((k8s_wait_ready_selector))

- name: kubernetes-delete
  serial: true
  max_in_flight: 1
  build_logs_to_retain: 10
  plan:
    - do:
      - get: git_config-k8s
        trigger: false

      - put: kubectl delete
        resource: k8s
        params:
          kubectl: |
            delete -f git_config-k8s/((k8s_path)) --recursive
          wait_until_ready_selector: ((k8s_wait_ready_selector))
