groups:

- name: overview
  jobs:
  - kubernetes-plan
  - kubernetes-apply

- name: destroy
  jobs:
  - kubernetes-delete

resource_types:

- name: kubernetes
  type: docker-image
  source:
    repository: cycloid/kubernetes-resource
    tag: ((k8s_version))

resources:

- name: git_config-k8s
  type: git
  icon: git
  source:
    uri: ((config_git_repository))
    branch: ((config_git_branch))
    private_key: ((config_git_private_key))
    paths:
      - ((k8s_path))/*

- name: k8s
  type: kubernetes
  icon: kubernetes
  source:
    kubeconfig: ((k8s_kubeconfig))
    gcp_credentials_json: ((gcp_credentials_json))

jobs:

- name: kubernetes-plan
  serial: true
  max_in_flight: 1
  build_logs_to_retain: 10
  plan:
    - do:
      - get: git_config-k8s
        trigger: true

      - task: download gcloud
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: alpine
              tag: latest
          run:
            path: sh
            args:
              - '-exc'
              - |
                apk add -q --no-cache --no-progress bash curl python which
                curl -sSL https://sdk.cloud.google.com > install.sh
                bash install.sh --disable-prompts --install-dir=./gcloud
          outputs:
            - name: gcloud

      - try:
          task: weaveworks kubediff
          config:
            platform: linux
            image_resource:
              type: docker-image
              source:
                repository: weaveworks/kubediff
                tag: latest
            run:
              path: sh
              args:
                - '-ec'
                - |
                  export PATH=$PWD/gcloud/google-cloud-sdk/bin:$PATH
                  echo "$GOOGLE_CREDENTIALS" > .gcp_credentials.json
                  gcloud auth activate-service-account --key-file=.gcp_credentials.json
                  echo "$KUBECONFIG" > .kubeconfig
                  kubediff --kubeconfig=.kubeconfig git_config-k8s/((k8s_path))
            inputs:
              - name: git_config-k8s
              - name: gcloud
          params:
            KUBECONFIG: ((k8s_kubeconfig))
            GOOGLE_CREDENTIALS: ((gcp_credentials_json))

      - try:
          put: kubectl diff
          resource: k8s
          params:
            kubectl: |
              diff -f git_config-k8s/((k8s_path)) --recursive

      - put: kubectl apply dry-run
        resource: k8s
        params:
          kubectl: |
            apply --server-dry-run -f git_config-k8s/((k8s_path)) --recursive
          wait_until_ready_selector: ((k8s_wait_ready_selector))

- name: kubernetes-apply
  serial: true
  max_in_flight: 1
  build_logs_to_retain: 10
  plan:
    - do:
      - get: git_config-k8s
        trigger: false
        passed:
          - kubernetes-plan

      - put: kubectl apply
        resource: k8s
        params:
          kubectl: |
            apply -f git_config-k8s/((k8s_path)) --recursive
          wait_until_ready_selector: ((k8s_wait_ready_selector))

- name: kubernetes-delete
  serial: true
  max_in_flight: 1
  build_logs_to_retain: 10
  plan:
    - do:
      - get: git_config-k8s
        trigger: false

      - put: kubectl delete
        resource: k8s
        params:
          kubectl: |
            delete -f git_config-k8s/((k8s_path)) --recursive
          wait_until_ready_selector: ((k8s_wait_ready_selector))
